 create database sampledatabase;
 Use sampledatabase;
 CREATE TABLE mytable1(
PersonID int,
LastName varchar(255),
FirstName varchar(255),
Address varchar(255),
City varchar(255));


create database genralattendance;
use genralattendance;

CREATE TABLE class1(
 Sno int,
 Roll_no int(255),
 student_name varchar(255),
 01_06_2023	varchar(255),
 05_06_2023	varchar(255),
 06_06_2023	varchar(255),
 07_06_2023 varchar(255),
 08_06_2023 varchar(255),
 12_06_2023 varchar(255),
 13_06_2023 varchar(255),
 14_06_2023 varchar(255),
 15_06_2023 varchar(255),
 19_06_2023 varchar(255),
 20_06_2023 varchar(255),
 21_06_2023 varchar(255),
 22_06_2023 varchar(255),
 26_06_2023 varchar(255),
 27_06_2023 varchar(255),
 28_06_2023 varchar(255),
 03_07_2023 varchar(255),
 04_07_2023 varchar(255),
 05_07_2023 varchar(255),
 06_07_2023 varchar(255),
 10_07_2023 varchar(255),
 11_07_2023 varchar(255),
 12_07_2023 varchar(255),
 13_07_2023 varchar(255),
 17_07_2023 varchar(255),
 18_07_2023 varchar(255),
 19_07_2023 varchar(255),
 20_07_2023 varchar(255),
 24_07_2023 varchar(255),
 25_07_2023 varchar(255));

INSERT INTO class1 
VALUES 
(1, 2231001, 'Aditya G', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(2, 2231002, 'Aneez I', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(3, 2231003, 'Ann Jerusha S', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(4, 2231004, 'Bhavatharini C', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(5, 2231005, 'Christabel Sharon R', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(6, 2231006, 'Danusri R', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(7, 2231007, 'Deepak Kumar A', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'A', 'P', 'P', 'P', 'A', 'A', 'A', 'A', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(8, 2231008, 'Dharaneesh R', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(9, 2231009, 'Dharshana S', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'A', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(10, 2231010, 'Dharun.S.', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(11, 2231011, 'Dhrisheta M S', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(12, 2231012, 'Dushyanth M', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(13, 2231013, 'Elancheliyan P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),

(14, 2231014, 'Gayathri S K', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(15, 2231015, 'Gokulanand M', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(16, 2231016, 'Gugan V', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),(17, 2231017, 'Jay Dheshiv A', 'P', 'A', 'P', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(18, 2231018, 'Jayant C Krishnan', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(19, 2231019, 'Kamaleshwaran S', 'P', 'A', 'P', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(20, 2231020, 'Karthikeyan.A.', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(21, 2231021, 'Kavin Kumar S', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(22, 2231022, 'Kavya Shree SP', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(23, 2231023, 'Kevin Joseph T', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(24, 2231024, 'Logeshwaran S', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(25, 2231025, 'Mitesh S', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(26, 2231026, 'Monetha V', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(27, 2231027, 'Moulidharan S', 'P', 'P', 'A', 'A', 'P', 'A', 'P', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(28, 2231028, 'Nivetha Sre M', 'P', 'P', 'A', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(29, 2231029, 'Nivethitha D', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null'),
(30, 2231030, 'Omega S', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null');

 CREATE TABLE class2(
 Sno int,
 Roll_no int(255),
 student_name varchar(255),
 01_06_2023	varchar(255),
 05_06_2023	varchar(255),
 06_06_2023	varchar(255),
 07_06_2023 varchar(255),
 08_06_2023 varchar(255),
 12_06_2023 varchar(255),
 13_06_2023 varchar(255),
 14_06_2023 varchar(255),
 15_06_2023 varchar(255),
 19_06_2023 varchar(255),
 20_06_2023 varchar(255),
 21_06_2023 varchar(255),
 22_06_2023 varchar(255),
 26_06_2023 varchar(255),
 27_06_2023 varchar(255),
 28_06_2023 varchar(255),
 03_07_2023 varchar(255),
 04_07_2023 varchar(255),
 05_07_2023 varchar(255),
 06_07_2023 varchar(255),
 10_07_2023 varchar(255),
 11_07_2023 varchar(255),
 12_07_2023 varchar(255),
 13_07_2023 varchar(255),
 17_07_2023 varchar(255),
 18_07_2023 varchar(255),
 19_07_2023 varchar(255),
 20_07_2023 varchar(255),
 24_07_2023 varchar(255),
 25_07_2023 varchar(255));
 
INSERT INTO class2
VALUES 
(1, 2232001, 'Pranaesh R', 'P', 'A', 'P', 'A', 'A', 'A', 'A', 'P', 'A', 'A', 'P', 'A', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(2, 2232002, 'Praneeth S S', 'P', 'A', 'P', 'A', 'A', 'A', 'A', 'P', 'P', 'A', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(3, 2232003, 'Prasanna Gokula Krishnan Y', 'P', 'A', 'P', 'A', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(4, 2232004, 'Priyadharshini G S', 'P', 'A', 'P', 'A', 'A', 'A', 'P', 'P', 'P', 'A', 'P', 'A', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(5, 2232005, 'Ranjith L K', 'P', 'A', 'P', 'A', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(6, 2232006, 'Rishvanthan R R', 'P', 'A', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(7, 2232007, 'Rithanyaa G V', 'P', 'A', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'A', 'A', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(8, 2232008, 'Rithikalaksmi K J', 'P', 'A', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(9, 2232009, 'Ruban S', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(10, 2232010, 'Sanjay R.', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(11, 2232011, 'Saran P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(12, 2232012, 'Saranya Devi.S.', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(13, 2232013, 'Saranya N', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(14, 2232014, 'Sathvik . A.', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(15, 2232015, 'Sevi Anto Jensima I', 'P', 'A', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'A', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(16, 2232016, 'Shiva Palaksha S G', 'P', 'A', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(17, 2232017, 'Shruthika V', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(18, 2232018, 'Sibiyenthal K', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(19, 2232019, 'Srikrishnan G', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(20, 2232020, 'Sriadhish R', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'A', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(21, 2232021, 'Subhitcha S', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'A', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(22, 2232022, 'Supreetha S', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'A', 'P', 'P', 'P', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(23, 2232023, 'Surya Prakash.V', 'P', 'P', 'P', 'A', 'P', 'P', 'A', 'A', 'P', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(24, 2232024, 'Swathi S', 'P', 'P', 'P', 'A', 'P', 'P', 'A', 'A', 'P', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(25, 2232025, 'Tharunika K.M.', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(26, 2232026, 'Vaisaali Priyankaa R', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(27, 2232027, 'Vikash V D', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(28, 2232028, 'Vishal M', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(29, 2232029, 'Vishnuvarthan N', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null'),
(30, 2232030, 'Yazeen Rizwan A', 'P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'A', 'P', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null', 'null','null');

select * from class1;
select * from class2;